// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
};

export type TreatmentRequest = {
  name: string;
  description: string;
  durationInMinutes: number;
  price: number;
};

export type TreatmentResponse = {
  id: number;
  name: string;
  description: string;
  durationInMinutes: number;
  price: number;
};

export type ValidationProblemDetails = {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
  errors?: {
    [key: string]: Array<string>;
  };
};

export type PostApiTreatmentsData = {
  body: TreatmentRequest;
  path?: never;
  query?: never;
  url: "/api/Treatments";
};

export type PostApiTreatmentsErrors = {
  /**
   * Bad Request
   */
  400: ValidationProblemDetails;
};

export type PostApiTreatmentsError =
  PostApiTreatmentsErrors[keyof PostApiTreatmentsErrors];

export type PostApiTreatmentsResponses = {
  /**
   * Created
   */
  201: TreatmentResponse;
};

export type PostApiTreatmentsResponse =
  PostApiTreatmentsResponses[keyof PostApiTreatmentsResponses];

export type GetApiTreatmentsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Treatments/{id}";
};

export type GetApiTreatmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiTreatmentsByIdError =
  GetApiTreatmentsByIdErrors[keyof GetApiTreatmentsByIdErrors];

export type GetApiTreatmentsByIdResponses = {
  /**
   * OK
   */
  200: TreatmentResponse;
};

export type GetApiTreatmentsByIdResponse =
  GetApiTreatmentsByIdResponses[keyof GetApiTreatmentsByIdResponses];

export type ClientOptions = {
  baseUrl: "https://localhost:7033" | "http://localhost:5241" | (string & {});
};
