// This file is auto-generated by @hey-api/openapi-ts

export type CreateTreatmentRequest = {
  name: string;
  description: string;
  price: number;
  durationInMinutes: number;
  treatmentType: TreatmentType;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type LoginResponse = {
  token: string;
  expiresAt: string;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
};

export type TreatmentResponse = {
  id: number;
  name: string;
  description: string;
  price: number;
  durationInMinutes: number;
  treatmentType: TreatmentType;
};

export type TreatmentType = number;

export type UpdateTreatmentRequest = {
  name: string;
  description: string;
  price: number;
  durationInMinutes: number;
  treatmentType: TreatmentType;
};

export type ValidationProblemDetails = {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
  errors?: {
    [key: string]: Array<string>;
  };
};

export type PostApiAuthLoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/Auth/login";
};

export type PostApiAuthLoginErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiAuthLoginError =
  PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
  /**
   * OK
   */
  200: LoginResponse;
};

export type PostApiAuthLoginResponse =
  PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiTreatmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Treatments";
};

export type GetApiTreatmentsResponses = {
  /**
   * OK
   */
  200: Array<TreatmentResponse>;
};

export type GetApiTreatmentsResponse =
  GetApiTreatmentsResponses[keyof GetApiTreatmentsResponses];

export type PostApiTreatmentsData = {
  body: CreateTreatmentRequest;
  path?: never;
  query?: never;
  url: "/api/Treatments";
};

export type PostApiTreatmentsErrors = {
  /**
   * Bad Request
   */
  400: ValidationProblemDetails;
};

export type PostApiTreatmentsError =
  PostApiTreatmentsErrors[keyof PostApiTreatmentsErrors];

export type PostApiTreatmentsResponses = {
  /**
   * Created
   */
  201: TreatmentResponse;
};

export type PostApiTreatmentsResponse =
  PostApiTreatmentsResponses[keyof PostApiTreatmentsResponses];

export type DeleteApiTreatmentsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Treatments/{id}";
};

export type DeleteApiTreatmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteApiTreatmentsByIdError =
  DeleteApiTreatmentsByIdErrors[keyof DeleteApiTreatmentsByIdErrors];

export type DeleteApiTreatmentsByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiTreatmentsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Treatments/{id}";
};

export type GetApiTreatmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiTreatmentsByIdError =
  GetApiTreatmentsByIdErrors[keyof GetApiTreatmentsByIdErrors];

export type GetApiTreatmentsByIdResponses = {
  /**
   * OK
   */
  200: TreatmentResponse;
};

export type GetApiTreatmentsByIdResponse =
  GetApiTreatmentsByIdResponses[keyof GetApiTreatmentsByIdResponses];

export type PutApiTreatmentsByIdData = {
  body: UpdateTreatmentRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Treatments/{id}";
};

export type PutApiTreatmentsByIdErrors = {
  /**
   * Bad Request
   */
  400: ValidationProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutApiTreatmentsByIdError =
  PutApiTreatmentsByIdErrors[keyof PutApiTreatmentsByIdErrors];

export type PutApiTreatmentsByIdResponses = {
  /**
   * OK
   */
  200: TreatmentResponse;
};

export type PutApiTreatmentsByIdResponse =
  PutApiTreatmentsByIdResponses[keyof PutApiTreatmentsByIdResponses];

export type ClientOptions = {
  baseUrl: "https://localhost:7033" | "http://localhost:5241" | (string & {});
};
